repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: starwitorg
    url: registry-1.docker.io/starwitorg
    oci: true
  - name: valkey
    url: https://valkey.io/valkey-helm/

helmDefaults:
  wait: true

environments:
  default:
    values:
      - namespace: urbalytix
        hostname: cluster.local
        tls: false
        auth:
          client_secret: {{ requiredEnv "CLIENT_SECRET" }}
          keycloakRealmUrlInternal: http://keycloak.auth.svc.cluster.local/realms/urbalytix
          keycloakRealmUrlExternal: https://auth.cluster.local/realms/urbalytix

        app:
          context_path: ""
          feature_collection:
            enabled: true
            endpoint: https://www.was-wob.de/apiNodes
            secret: {{ requiredEnv "FEATURE_COLLECTION_SECRET" }}
          spring_data: # Configuration to connect to Redis/ValKey
            redis_active: true # if true connection config is used
            stream_prefix: aggregator
            redis_host: valkey.urbalytix.svc.cluster.local
            redis_port: 6379
            aggregator_stream_prefix: aggregator # if aggregation messages are published under a different name
            positionsource_stream_prefix: positionsource # if position messages are published under a different name
            detection_stream_prefix: objectdetector # if detection messages are published under a different name
        dbpasswords: 
          postgres: {{ requiredEnv "DB_ROOT_PASSWORD" }}
          urbalytix: {{ requiredEnv "DB_URBALYTIX_SECRET" }}
        dashboard:
          domain_prefix: grafana
        valkey_enabled: true
  wob-staging:
    values:
      - namespace: urbalytix
        hostname: staging.data-wolfsburg.de
        tls: false
        auth:
          client_secret: {{ requiredEnv "CLIENT_SECRET" }}
          keycloakRealmUrlInternal: http://keycloak.observatory-data.svc.cluster.local/realms/urbalytix
          keycloakRealmUrlExternal: https://auth.staging.data-wolfsburg.de/realms/urbalytix

        app:
          context_path: ""
          feature_collection:
            enabled: true
            endpoint: https://www.was-wob.de/apiNodes
            secret: {{ requiredEnv "FEATURE_COLLECTION_SECRET" }}
          spring_data: # Configuration to connect to Redis/ValKey
            redis_active: true # if true connection config is used
            stream_prefix: aggregator
            redis_host: valkey-primary.observatory-data.svc.cluster.local
            redis_port: 6379
            aggregator_stream_prefix: aggregator # if aggregation messages are published under a different name
            positionsource_stream_prefix: positionsource # if position messages are published under a different name
            detection_stream_prefix: objectdetector # if detection messages are published under a different name
        dbpasswords: 
          urbalytix: {{ requiredEnv "DB_URBALYTIX_SECRET" }}
        dashboard:
          domain_prefix: grafana
        valkey_enabled: false # means there is already a valkey/redis instance

---
releases:
  - name: urbalytix
    installed: true
    namespace: {{ .Values.namespace }}
    chart: starwitorg/urbalytix-chart 
    version: 0.4.1
    values:
      - image:
          tag: 0.4.1
        app:
          context_path: {{ .Values.app.context_path | default "" }}
          feature_collection:
            enabled: {{ .Values.app.feature_collection.enabled }}
            endpoint: {{ .Values.app.feature_collection.endpoint }}
            secret: {{ .Values.app.feature_collection.secret }}
          spring_data: # Configuration to connect to Redis/ValKey
            redis_active: {{ .Values.app.spring_data.redis_active | default false}}
            stream_prefix: {{ .Values.app.spring_data.stream_prefix | default "aggregator" }}
            redis_host: {{ .Values.app.spring_data.redis_host | default "valkey-primary.observatory-data.svc.cluster.local" }}
            redis_port: {{ .Values.app.spring_data.redis_port | default 6379 | int }}
            aggregator_stream_prefix: {{ .Values.app.spring_data.aggregator_stream_prefix | default "aggregator" }}
            positionsource_stream_prefix: {{ .Values.app.spring_data.positionsource_stream_prefix | default "positionsource" }}
            detection_stream_prefix: {{ .Values.app.spring_data.detection_stream_prefix | default "objectdetector" }}
        auth:
          enabled: true
          keycloakRealmUrlInternal: {{ .Values.auth.keycloakRealmUrlInternal }}
          keycloakRealmUrlExternal: {{ .Values.auth.keycloakRealmUrlExternal }}
          clientId: urbalytix
          clientSecret: {{ .Values.auth.client_secret }}
        database:
          hostname: timescaledb-chart-timescale.{{ .Values.namespace }}.svc.cluster.local
          port: 5432
          database: urbalytix
          username: urbalytix
          password: {{ .Values.dbpasswords.urbalytix }}

        ingress:
          enabled: true
          hosts:
            - host: urbalytix.{{ .Values.hostname }}
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - hosts:
              - spc.{{ .Values.hostname }}
              secretName: urbalytix.{{ .Values.hostname }}
        extraEnv: |
          - name: SERVER_COMPRESSION_ENABLED
            value: "true"

  - name: timescale
    installed: true
    namespace: {{ .Values.namespace }}
    chart: starwitorg/timescaledb-chart
    version: 1.2.4
    values:
      - postgresql:
          password: {{ .Values.dbpasswords.urbalytix }}
        init:
          enabled: true
          init_user_db: |
            -- Create schemata, users and extenions
            CREATE EXTENSION IF NOT EXISTS timescaledb;
            CREATE EXTENSION postgis;
            CREATE USER urbalytix WITH PASSWORD '{{ .Values.dbpasswords.urbalytix }}';    
            CREATE DATABASE "urbalytix" owner urbalytix;

          init_tables: |  
            -- empty
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"

  - name: valkey
    installed: {{ .Values.valkey_enabled }}
    namespace: {{ .Values.namespace }}
    chart: valkey/valkey